### ISSUE TITLE
[Intent] What music services do you support?

### ISSUE THREAD

**Issue by awallin** [mozilla-extensions/firefox-voice#1268]
People are asking what music services are supported. The results should be displayed in a card with the ability to set a default. See mockup for details. Of note:

* Music services support will be growing over time so the query should current the current status at the time of request.
* Clicking on an icon/name should set the default music service. A hint to this affect is displayed at the bottom of the card.
* Attaching icons for the major services (even if we don't support them yet)

[music service.zip](https://github.com/mozilla/firefox-voice/files/4326752/music.service.zip)

![music-provider](https://user-images.githubusercontent.com/428245/76590643-12740500-64ab-11ea-8a00-984110f98562.jpg)

**Comment by Simpcyclassy** [comment]
Some neat UI work here, if by the time I am done with my pending tasks and this is not done please I will love to give it a shot.

**Comment by GangaChatrvedi** [comment]
I would love to work on this issue

**Comment by awallin** [comment]
All yours @GangaChatrvedi

**Comment by awallin** [comment]
Made a few edits to the mockup to use a vertical list which will serve us better in the long run for other questions that result in multiple answers/choices. This card can serve as a template for future needs.

Also in #962 @JM-Mendez is trying to allow for follow up responses which this is a good example of. He can implement or point you to the proper implementation for this.

**Comment by JM-Mendez** [comment]
@GangaChatrvedi I'm currently working on adding the vocal follow up responses (it will be the component below "did we get this right"). Currently the recorder stops listening after the initial run of the intent, so I'll have to refactor that part of the codebase to listen for follow up responses and respond accordingly. I'm don't know how you plan to implement the fix for this issue, or if any of my proposed changes will collide with yours. So if you don't mind reaching out to me, I'd appreciate it.

**Comment by GangaChatrvedi** [comment]
@JM-Mendez I would love to collaborate and make it as awesome as possible

**Comment by JM-Mendez** [comment]
@GangaChatrvedi awesome! I invited you to a chat on matrix. We can pick back up there.

**Comment by awallin** [comment]
Another utterance to match for this:
* what streaming radio do you have

**Comment by Simpcyclassy** [comment]
@awallin are you going to provide the icons or do I set a direct link  to the service
