### ISSUE TITLE
[Intent] Hello

### ISSUE THREAD

**Issue by awallin** [mozilla-extensions/firefox-voice#1269]
People often say 'hello' to Firefox Voice. We should have a joy filled moment. See attached mockup.

Details include:
* Lionel Richie saying "Is it me your looking for?"
* Education to teach what else can be said: "Click mic and say ‘help’ for things to say"

![hello](https://user-images.githubusercontent.com/428245/76588780-2fa5d500-64a5-11ea-9f43-ad823bdedbb9.jpg)
![Lionel Richie](https://user-images.githubusercontent.com/428245/76588782-303e6b80-64a5-11ea-8c08-168c458653f9.jpg)

**Comment by saucekode** [comment]
Lol @awallin can I take this? Sounds like fun

**Comment by awallin** [comment]
All yours @saucekode. I can't wait to see it in action.

**Comment by awallin** [comment]
Made a few changes to the content and visual layout for this to establish a template for Q&A cards used in #1266 #1267 and #1270. Specs for these cards are as follows:

* 100x100 image with
* 25px of padding between Question Transcript and image
* 35px of padding between image and Answer text

**Comment by saucekode** [comment]
@awallin please take a look at this and review. Thank you

**Comment by awallin** [comment]
@saucekode This look great. So fun. @ianb take a look and merge if it looks good to you.

**Comment by jcambre** [comment]
Janice pointed out today that this actually took over the whole "help"-type intent, so that when you say "help" or "what can I say," you get Lionel Ritchie instead of the expected behavior of opening the lexicon. We should separate out "hello" into it's own separate intent.
