### ISSUE TITLE
[Intermittent] Negative feedback display for "Timer" command not shown

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla-extensions/firefox-voice#1387]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a "Timer" command, e.g. "Set timer for 20 seconds", "Timer for 10 seconds".
3. Click the sad emoticon from "Did we get this right" section. 

### Expected result:
The negative feedback display is shown in the doorhanger.

### Actual result:
Doorhanger display is minimised. 

### Notes:
Reproduced intermittently 8, 9 or 10 times out of 10 on Mac 10.14 with Firefox Nightly 76.0a1 (2020-03-26).
If doorhanger is not dismissed when in the minimised state, the finished "Timer" display will not be visible. (2nd gif)

![14](https://user-images.githubusercontent.com/54401091/77657840-84a21a80-6f7e-11ea-8303-61848f164802.gif)

![9](https://user-images.githubusercontent.com/54401091/77655727-76063400-6f7b-11ea-89f7-7527a0f54957.gif)

**Comment by naima-shk** [comment]
@ianb  Can i try this one please?

**Comment by Simpcyclassy** [comment]
Let me work on this please @ianb

**Comment by awallin** [comment]
Go for it @Simpcyclassy

**Comment by Simpcyclassy** [comment]
Alright, looking into it now

**Comment by Simpcyclassy** [comment]
This is a weird bug cause in some instances especially when the timer is up to 1 minute it does show. I think this instability is somehow calling cancel in a way I am still trying to figure out. I am taking a closer look at popupView as to how the Feedback component is being called
