### ISSUE TITLE
Feedback card is shown when typing in doorhanger

### ISSUE THREAD

**Issue by danielamormocea** [mozilla-extensions/firefox-voice#1509]
Now, in some cases, the card with "Did we get this right?" is shown and some errors appear when clicking on the feedback faces.

Steps to reproduce:

1. Have in the preferences the "Keep the microphone on for follow up responses" checked
2. Open the doorhanger
3. Type anything

Expected result: 
No feedback card is displayed.

Actual result:
Feedback is displayed.

![bug](https://user-images.githubusercontent.com/38378382/78812021-710d9f80-79d3-11ea-940c-ee1e90c9a12f.png)

**Comment by alexandra-martin** [comment]
Can confirm, using the described steps, I am able to reproduce the issue on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-08).

![1](https://user-images.githubusercontent.com/54401091/78894467-c0a4a780-7a75-11ea-8da9-ba9b33487540.gif)
