### ISSUE TITLE
Spotify Play command only works with Spotify on English

### ISSUE THREAD

**Issue by Vuelos** [mozilla-extensions/firefox-voice#1602]
![imagen](https://user-images.githubusercontent.com/8868919/80655652-98491100-8a55-11ea-97a2-def601730c3b.png)

Here is a screen capture where you can see the error:

`Internal error: Error: Could not find element a[aria-label='Search']`

with the command "Play Madonna in Spotify", the Insperctor in the Button shows:

`<a class="link-subtle navBar-link ellipsis-one-line navBar-link--active" aria-label="Buscar" href="/search" aria-current="page">
`
Being aria-label="Buscar" in my case (Spanish) instead of aria-label="Search"

Maybe changing in extension/services/spotify/player.js line 19:
```

 const searchButton = await this.waitForSelector(
        "a[aria-label='Search']",
        {
          timeout: 5000,
        }
      );
      searchButton.click();
```

to search for "href=/Search" can solve it.

**Comment by melvin2016** [comment]
Let me look at it.
