### ISSUE TITLE
"Show notes" give invalid tab error if notes tab is closed

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla-extensions/firefox-voice#1643]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.
An online notepad tab is made the default tab where notes are added with the "Make notes here" command. Another tab is then made active and the notes tab is closed.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the "Show notes" command.

### Expected result:
The default tab where notes are added opens without issues.

### Actual result:
"Internal error: Error: Invalid tab ID: 6" is displayed in the doorhanger.

### Notes:
Reproduced on Mac 10.14 and Windows 10x64 with Firefox Nightly 78.0a1 (2020-05-12).
The number from the error message may be different depending on the tab used.
If the default tab where notes are added is closed and an "Add note" command is made, "The writing tab has changed, use "show notes" and "write notes here"" is displayed in the doorhanger.

![5](https://user-images.githubusercontent.com/54401091/81816305-d2c1ac00-9533-11ea-9553-48af64e49b52.gif)

**Comment by AbhiVaidya95** [comment]
@alexandra-martin Do we need to reopen the Notes tab which was closed is that what's expected?

**Comment by AbhiVaidya95** [comment]
@ianb I have made the changes can you please confirm if there are right?
Thanks.
![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/65556960/87671860-ae7e8780-c78f-11ea-830c-5ce4c23d6b07.gif)
