### ISSUE TITLE
"How many tabs do I have open" should report all tabs, not just the ones in the current window

### ISSUE THREAD

**Issue by jofish** [mozilla-extensions/firefox-voice#1776]
Right now, "How many tabs do I have open" reports one number, the number of tabs in the current window. 

We should report the number of tabs in _all_ open Firefox windows ("You have 33 tabs in 4 windows"); optionally we could additionally report the number of tabs in the local window ("You have 33 tabs in 4 windows, of which 8 are in this window.")

**Comment by PascalUlor** [comment]
Can I work on this please?

**Comment by Ishakikani9117** [comment]
@ianb  Can I work on this issue?

**Comment by PascalUlor** [comment]
@Simpcyclassy @ianb  is this issue still available? I'm interested

**Comment by Simpcyclassy** [comment]
It is still available @PascalUlor since you asked first, go for it.
