### ISSUE TITLE
Phrase: [time] minutes should start a timer

### ISSUE THREAD

**Issue by ianb** [mozilla-extensions/firefox-voice#1824]
If you forget to say (or it is cutoff) "set timer", then the time alone should open the timer. Evidence: [this search result](https://www.google.com/search?client=firefox-b-1-d&q=5+minutes) for 5 minutes only points to timers.

**Comment by AbhiVaidya95** [comment]
@ianb I have tried add the functionality,Can you please give a loot at it/
![ezgif com-video-to-gif (5)](https://user-images.githubusercontent.com/65556960/88314682-e73fd300-cd32-11ea-95ef-024d675bff14.gif)
