### ISSUE TITLE
[Intent] add X to clipboard

### ISSUE THREAD

**Issue by ianb** [mozilla-extensions/firefox-voice#1829]
This would be a series of clipboard actions: add selection to clipboard, add link to clipboard, add title to clipboard.

In terms of implementation, each of these has to load the clipboard content, add the appropriate text to the end (separated by a newline), and then write to the clipboard. I think these should only allow for text, and not worry about rich text or images.

For inserting newlines, the code should avoid blank lines, including handling an empty starting clipboard.

**Comment by AbhiVaidya95** [comment]
@ianb I have made changes and its working for Selection,Link and Title.
Kindly let me know in case of some changes, Thanks.
![ezgif com-video-to-gif (7)](https://user-images.githubusercontent.com/65556960/88466108-b3a5aa00-cee6-11ea-93dc-310c55223983.gif)
