### ISSUE TITLE
Wakeword pinned tab

### ISSUE THREAD

**Issue by awallin** [mozilla-extensions/firefox-voice#1854]
For microphone permissions wakeword detection requires a pinned tab for listening. The pinned tab should explain 3 things:
* Make it clear the tab is listening for a specific wakeword (e.g. "Hey Firefox")
* Explain why the pinned tab is needed
* Educate people on what they can say (because we should take the opportunity)

See mockup for specific design details and layout. [Content is available in the content doc](https://docs.google.com/document/d/17MnBTuO4Mxl7HZbYF6nxMVtni-MzuYLHkjtauvKiqxs/edit?usp=sharing) for Copy and Paste.

![Wakeword listening-v2](https://user-images.githubusercontent.com/428245/88706030-28363f80-d0c5-11ea-80c9-ba2fbf705cb8.jpg)

**Comment by jcambre** [comment]
@awallin should we pick a few additional examples to go under "Try saying things like"? I'm also thinking that those should all read "Hey Firefox, [example here]"
