### ISSUE TITLE
Rename bangSearch to serviceSearch

### ISSUE THREAD

**Issue by ianb** [mozilla-extensions/firefox-voice#442]
"Bang" doesn't mean anything to other people.

**Comment by lelouchB** [comment]
Hey @ianb  I am Ashutosh, Outreachy Applicant and want to work on this issue

**Comment by ianb** [comment]
@lelouchB Let's not do this one right now – there's a lot of people working in the code right now so this kind of refactoring will cause merge conflicts.

**Comment by lelouchB** [comment]
@ianb okay will move to another issue
